/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap.repeated.word;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");



        // testing for repeatedWord function
        String test = "Once upon a time, there was a brave princess who...";
        assertEquals("a",App.repeatedWord(test));

        String test2 = "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only...";
        assertEquals("it",App.repeatedWord(test2));

        String test3 = "It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York...";
        assertEquals("summer",App.repeatedWord(test3));

        // testing if the string doesnt have a repeated words, it should return null
        String test4 = "I wish that my death will make more cents than ma life";
        assertNull(App.repeatedWord(test4));
    }
}
