/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap.repeated.word;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
/
        String words = "It was the best of times, it was the worst of times,";
        System.out.println(repeatedWord(words));
    }


    public static String  repeatedWord(String words){
        HashMap<String,Integer> array = new HashMap<>();
        String result = null;

        String[] arrayOfWords = words.split(" ");

        for (int i = 0; i < arrayOfWords.length; i++) {

            if (arrayOfWords[i].contains(",")){
                arrayOfWords[i] = deleteComaFromString(arrayOfWords[i]);
            }


            if (array.containsKey(arrayOfWords[i].toLowerCase())){
                result = arrayOfWords[i];
                break;
            }else{
                array.put(arrayOfWords[i].toLowerCase(),i);
            }
        }
     return result;
    }




    public static String deleteComaFromString(String str){
        str = str.substring(0, str.length() - 1);
        return str;
    }
}
