/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap.left.join;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        HashMap<String,String> hashmap1 = new HashMap<>();
        HashMap<String,String> hashmap2 = new HashMap<>();

        hashmap1.put("fond","enamored");
        hashmap1.put("wrath","anger");
        hashmap1.put("diligent","employed");
        hashmap1.put("outfit","garb");
        hashmap1.put("guide","usher");

        hashmap2.put("fond","averse");
        hashmap2.put("wrath","delight");
        hashmap2.put("diligent","idle");
        hashmap2.put("guide","follow");
        hashmap2.put("flow","jam");


        System.out.println(hashmap1.toString());
        System.out.println(hashmap2.toString());
        System.out.println((leftJoin(hashmap1,hashmap2)).toString());

    }


    public static List leftJoin(HashMap hashOne , HashMap hashTwo){
        List<String> result = new ArrayList<>();
        hashOne.forEach((key,value)->{
            if (hashTwo.containsKey(key)){
                result.add(key + ": " + value + " , " + hashTwo.get(key) + "\n");
            }else{
                result.add(key + ": " + value + " , " + "Null"+ "\n");
            }
        });

        return result;
    }
}
