/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {


        Stack<Integer> newS = new Stack<>();
        newS.push(4);
        System.out.println(newS.top.value);
        newS.pop();
        System.out.println(newS.isEmpty());



        Queue<Integer> newQ = new Queue<>();
        newQ.enqueue(6);
        System.out.println(newQ.dequeue());





    }
}
