/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");

        // empty linked list test
        LinkedList test = new LinkedList();
        assertNull(test.head);


        //Can properly insert into the linked list
        test.insert(4);
        assertEquals(4, test.head.value);


        //The head property will properly point to the first node
        assertEquals(4, test.head.value);
        assertNull(test.head.next);


        //Can properly insert multiple nodes into the linked list
        test.insert(3);
        test.insert(2);
        assertEquals(2,test.head.value);


        //Will return true when finding a value within the linked list that exists
        assertTrue(test.includes(3));


        //Will return false when searching for a value in the linked list that does not exist
        assertFalse(test.includes(20));


        //Can properly return a collection of all the values that exist in the linked list
        assertEquals("{2} -> {3} -> {4} -> NULL" , test.toString());

    }
}



