/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }


    public static void main(String[] args) throws Exception {

        LinkedList testList = new LinkedList();
        testList.insert(5);
        testList.insert(3);
        testList.insert(2);

        testList.append(1);
        testList.insertBefore(1,4);

        testList.insertAfter(13,14);

//        System.out.println(testList.includes(3));

        System.out.println(testList.toString());

        System.out.println(testList.kthFromEnd(2));
    }
}
